### PR TITLE
add negative word 

### PR DESCRIPTION
**Pull request by yebityon**

### CODE REVIEW

**Comment by bloodb4th** [comment]
Sorry,
"To test the hypothesis ... we performed a lot of assingnment test " is a positive sentiment according to monkey learn

**Comment by bloodb4th** [comment]
Try to also edit 1 line only

**Comment by yebityon** [comment]
oh..... monkey learn really likes assignments. 
I'll fix it soon.

**Comment by bloodb4th** [comment]
Careful. I edit a new file while you are doing things

**Comment by yebityon** [comment]
hope I have no conflict :)

**Comment by bloodb4th** [comment]
Whoops, sorry i think some one take your blank spot. can you pull again my update and edit the one at the last sentence?

**Comment by yebityon** [comment]
fix it.

**Comment by bloodb4th** [comment]
Thanks a lot. Do you need more help for fixing stuff?

**Comment by yebityon** [comment]
You're welcome !!

**Pull request merged**
